[project]
name = "little-x"
version = "1.0.0"
description = "Jac client application: little-x"
entry-point = "main.jac"

[plugins.client]

[dependencies.npm]
jac-client-node = "1.0.7"
lodash = "latest"
antd = "latest"
pluralize = "latest"
react-animated-components = "latest"
styled-components = "latest"

[dependencies.npm.dev]
"@jac-client/dev-deps" = "2.0.0"

[serve]
base_route_app = "jac_app"
